import {
  array,
  boolean,
  int,
  literal,
  maximum,
  minimum,
  nullable,
  number,
  object,
  partial,
  prettifyError,
  string,
  tuple,
  union,
  enum as zenum,
} from "zod/mini";
import type { MonacoEditor } from "../monacoSetup";
import { mergeDefined } from "../core/mergeDefined";

type EditorSettings = MonacoEditor.IStandaloneEditorConstructionOptions;

const defaultEditorSettings: EditorSettings = {};

// JSON editor settings schema
const autoClosingStrategySchema = zenum([
  "always",
  "languageDefined",
  "beforeWhitespace",
  "never",
]);
const gotoLocationValuesSchema = zenum(["peek", "gotoAndPeek", "goto"]);
const gotoLocationCommandSchema = zenum([
  "",
  "editor.action.referenceSearch.trigger",
  "editor.action.goToReferences",
  "editor.action.peekImplementation",
  "editor.action.goToImplementation",
  "editor.action.peekTypeDefinition",
  "editor.action.goToTypeDefinition",
  "editor.action.peekDeclaration",
  "editor.action.revealDeclaration",
  "editor.action.peekDefinition",
  "editor.action.revealDefinitionAside",
  "editor.action.revealDefinition",
]);
const editorSettingsSchema = partial(
  object({
    "editor.tabSize": number().check(minimum(1), maximum(100)),
    "editor.indentSize": union([
      zenum(["tabSize"]),
      number().check(minimum(1)),
    ]),
    "editor.insertSpaces": boolean(),
    "editor.detectIndentation": boolean(),
    "editor.trimAutoWhitespace": boolean(),
    "editor.largeFileOptimizations": boolean(),
    "editor.wordBasedSuggestions": zenum([
      "off",
      "currentDocument",
      "matchingDocuments",
      "allDocuments",
    ]),
    "editor.semanticHighlighting.enabled": union([
      boolean(),
      literal("configuredByTheme"),
    ]),
    "editor.stablePeek": boolean(),
    "editor.maxTokenizationLineLength": int(),
    "editor.experimental.asyncTokenization": boolean(),
    "editor.experimental.asyncTokenizationLogging": boolean(),
    "editor.experimental.asyncTokenizationVerification": boolean(),
    "editor.experimental.treeSitterTelemetry": boolean(),
    "editor.experimental.preferTreeSitter.css": boolean(),
    "editor.experimental.preferTreeSitter.typescript": boolean(),
    "editor.experimental.preferTreeSitter.ini": boolean(),
    "editor.experimental.preferTreeSitter.regex": boolean(),
    "editor.language.brackets": nullable(array(tuple([string(), string()]))),
    "editor.language.colorizedBracketPairs": nullable(
      array(tuple([string(), string()]))
    ),
    "editor.acceptSuggestionOnCommitCharacter": boolean(),
    "editor.acceptSuggestionOnEnter": zenum(["on", "smart", "off"]),
    "editor.accessibilitySupport": zenum(["auto", "on", "off"]),
    "editor.accessibilityPageSize": int().check(
      minimum(1),
      maximum(1073741824)
    ),
    "editor.allowVariableLineHeights": boolean(),
    "editor.allowVariableFonts": boolean(),
    "editor.allowVariableFontsInAccessibilityMode": boolean(),
    "editor.autoClosingBrackets": autoClosingStrategySchema,
    "editor.autoClosingComments": autoClosingStrategySchema,
    "editor.screenReaderAnnounceInlineSuggestion": boolean(),
    "editor.autoClosingDelete": zenum(["always", "auto", "never"]),
    "editor.autoClosingOvertype": zenum(["always", "auto", "never"]),
    "editor.autoClosingQuotes": autoClosingStrategySchema,
    "editor.autoIndent": zenum([
      "none",
      "keep",
      "brackets",
      "advanced",
      "full",
    ]),
    "editor.autoIndentOnPaste": boolean(),
    "editor.autoIndentOnPasteWithinString": boolean(),
    "editor.autoSurround": zenum([
      "languageDefined",
      "quotes",
      "brackets",
      "never",
    ]),
    "editor.bracketPairColorization.enabled": boolean(),
    "editor.bracketPairColorization.independentColorPoolPerBracketType":
      boolean(),
    "editor.guides.bracketPairs": union([
      boolean(),
      union([boolean(), literal("active")]),
    ]),
    "editor.guides.bracketPairsHorizontal": union([
      boolean(),
      union([boolean(), literal("active")]),
    ]),
    "editor.guides.highlightActiveBracketPair": boolean(),
    "editor.guides.indentation": boolean(),
    "editor.guides.highlightActiveIndentation": union([
      boolean(),
      union([boolean(), literal("always")]),
    ]),
    "editor.codeLens": boolean(),
    "editor.codeLensFontFamily": string(),
    "editor.codeLensFontSize": int().check(minimum(0), maximum(100)),
    "editor.colorDecorators": boolean(),
    "editor.colorDecoratorsLimit": int().check(minimum(1), maximum(1000000)),
    "editor.columnSelection": boolean(),
    "editor.comments.insertSpace": boolean(),
    "editor.comments.ignoreEmptyLines": boolean(),
    "editor.copyWithSyntaxHighlighting": boolean(),
    "editor.cursorBlinking": zenum([
      "blink",
      "smooth",
      "phase",
      "expand",
      "solid",
    ]),
    "editor.cursorSmoothCaretAnimation": zenum(["off", "explicit", "on"]),
    "editor.cursorStyle": zenum([
      "line",
      "block",
      "underline",
      "line-thin",
      "block-outline",
      "underline-thin",
    ]),
    "editor.cursorSurroundingLines": int().check(
      minimum(0),
      maximum(1073741824)
    ),
    "editor.cursorSurroundingLinesStyle": zenum(["default", "all"]),
    "editor.cursorWidth": int().check(minimum(0), maximum(1073741824)),
    "editor.cursorHeight": int().check(minimum(0), maximum(1073741824)),
    "editor.dragAndDrop": boolean(),
    "editor.dropIntoEditor.enabled": boolean(),
    "editor.dropIntoEditor.showDropSelector": zenum(["afterDrop", "never"]),
    "editor.editContext": boolean(),
    "editor.emptySelectionClipboard": boolean(),
    "editor.experimentalGpuAcceleration": zenum(["off", "on"]),
    "editor.experimentalWhitespaceRendering": zenum(["svg", "font", "off"]),
    "editor.fastScrollSensitivity": number(),
    "editor.find.cursorMoveOnType": boolean(),
    "editor.find.seedSearchStringFromSelection": zenum([
      "never",
      "always",
      "selection",
    ]),
    "editor.find.autoFindInSelection": zenum(["never", "always", "multiline"]),
    "editor.find.addExtraSpaceOnTop": boolean(),
    "editor.find.loop": boolean(),
    "editor.find.history": zenum(["never", "workspace"]),
    "editor.find.replaceHistory": zenum(["never", "workspace"]),
    "editor.find.findOnType": boolean(),
    "editor.folding": boolean(),
    "editor.foldingStrategy": zenum(["auto", "indentation"]),
    "editor.foldingHighlight": boolean(),
    "editor.foldingImportsByDefault": boolean(),
    "editor.foldingMaximumRegions": int().check(minimum(10), maximum(65000)),
    "editor.unfoldOnClickAfterEndOfLine": boolean(),
    "editor.fontFamily": string(),
    "editor.fontLigatures": union([boolean(), string()]),
    "editor.fontSize": number().check(minimum(6), maximum(100)),
    "editor.fontWeight": union([
      number().check(minimum(1), maximum(1000)),
      string(),
      zenum([
        "normal",
        "bold",
        "100",
        "200",
        "300",
        "400",
        "500",
        "600",
        "700",
        "800",
        "900",
      ]),
    ]),
    "editor.fontVariations": union([boolean(), string()]),
    "editor.formatOnPaste": boolean(),
    "editor.formatOnType": boolean(),
    "editor.glyphMargin": boolean(),
    "editor.gotoLocation.multipleDefinitions": gotoLocationValuesSchema,
    "editor.gotoLocation.multipleTypeDefinitions": gotoLocationValuesSchema,
    "editor.gotoLocation.multipleDeclarations": gotoLocationValuesSchema,
    "editor.gotoLocation.multipleImplementations": gotoLocationValuesSchema,
    "editor.gotoLocation.multipleReferences": gotoLocationValuesSchema,
    "editor.gotoLocation.alternativeDefinitionCommand":
      gotoLocationCommandSchema,
    "editor.gotoLocation.alternativeTypeDefinitionCommand":
      gotoLocationCommandSchema,
    "editor.gotoLocation.alternativeDeclarationCommand":
      gotoLocationCommandSchema,
    "editor.gotoLocation.alternativeImplementationCommand":
      gotoLocationCommandSchema,
    "editor.gotoLocation.alternativeReferenceCommand":
      gotoLocationCommandSchema,
    "editor.hideCursorInOverviewRuler": boolean(),
    "editor.hover.enabled": boolean(),
    "editor.hover.delay": number().check(minimum(0), maximum(10000)),
    "editor.hover.sticky": boolean(),
    "editor.hover.hidingDelay": int().check(minimum(0)),
    "editor.hover.above": boolean(),
    "editor.inlineSuggest.enabled": boolean(),
    "editor.inlineSuggest.showToolbar": zenum(["always", "onHover", "never"]),
    "editor.inlineSuggest.syntaxHighlightingEnabled": boolean(),
    "editor.inlineSuggest.suppressSuggestions": boolean(),
    "editor.inlineSuggest.suppressInSnippetMode": boolean(),
    "editor.inlineSuggest.minShowDelay": number().check(
      minimum(0),
      maximum(10000)
    ),
    "editor.inlineSuggest.experimental.suppressInlineSuggestions": string(),
    "editor.inlineSuggest.experimental.emptyResponseInformation": boolean(),
    "editor.inlineSuggest.triggerCommandOnProviderChange": boolean(),
    "editor.inlineSuggest.experimental.showOnSuggestConflict": zenum([
      "always",
      "never",
      "whenSuggestListIsIncomplete",
    ]),
    "editor.inlineSuggest.fontFamily": string(),
    "editor.inlineSuggest.edits.allowCodeShifting": zenum([
      "always",
      "horizontal",
      "never",
    ]),
    "editor.inlineSuggest.edits.renderSideBySide": zenum(["auto", "never"]),
    "editor.inlineSuggest.edits.showCollapsed": boolean(),
    "editor.letterSpacing": number(),
    "editor.lightbulb.enabled": zenum(["off", "onCode", "on"]),
    "editor.lineHeight": number().check(minimum(0), maximum(150)),
    "editor.lineNumbers": zenum(["off", "on", "relative", "interval"]),
    "editor.linkedEditing": boolean(),
    "editor.links": boolean(),
    "editor.matchBrackets": zenum(["always", "near", "never"]),
    "editor.minimap.enabled": boolean(),
    "editor.minimap.autohide": zenum(["none", "mouseover", "scroll"]),
    "editor.minimap.size": zenum(["proportional", "fill", "fit"]),
    "editor.minimap.side": zenum(["left", "right"]),
    "editor.minimap.showSlider": zenum(["always", "mouseover"]),
    "editor.minimap.scale": number().check(minimum(1), maximum(3)),
    "editor.minimap.renderCharacters": boolean(),
    "editor.minimap.maxColumn": number(),
    "editor.minimap.showRegionSectionHeaders": boolean(),
    "editor.minimap.showMarkSectionHeaders": boolean(),
    "editor.minimap.markSectionHeaderRegex": string(),
    "editor.minimap.sectionHeaderFontSize": number(),
    "editor.minimap.sectionHeaderLetterSpacing": number(),
    "editor.mouseWheelScrollSensitivity": number(),
    "editor.mouseWheelZoom": boolean(),
    "editor.multiCursorMergeOverlapping": boolean(),
    "editor.multiCursorModifier": zenum(["ctrlCmd", "alt"]),
    "editor.mouseMiddleClickAction": zenum([
      "default",
      "openLink",
      "ctrlLeftClick",
    ]),
    "editor.multiCursorPaste": zenum(["spread", "full"]),
    "editor.multiCursorLimit": int().check(minimum(1), maximum(100000)),
    "editor.occurrencesHighlight": zenum(["off", "singleFile", "multiFile"]),
    "editor.occurrencesHighlightDelay": int().check(minimum(0), maximum(2000)),
    "editor.overtypeCursorStyle": zenum([
      "line",
      "block",
      "underline",
      "line-thin",
      "block-outline",
      "underline-thin",
    ]),
    "editor.overtypeOnPaste": boolean(),
    "editor.overviewRulerBorder": boolean(),
    "editor.padding.top": number().check(minimum(0), maximum(1000)),
    "editor.padding.bottom": number().check(minimum(0), maximum(1000)),
    "editor.pasteAs.enabled": boolean(),
    "editor.pasteAs.showPasteSelector": zenum(["afterPaste", "never"]),
    "editor.parameterHints.enabled": boolean(),
    "editor.parameterHints.cycle": boolean(),
    "editor.peekWidgetDefaultFocus": zenum(["tree", "editor"]),
    "editor.definitionLinkOpensInPeek": boolean(),
    "editor.quickSuggestions": object({
      strings: union([boolean(), zenum(["on", "inline", "off"])]),
      comments: union([boolean(), zenum(["on", "inline", "off"])]),
      other: union([boolean(), zenum(["on", "inline", "off"])]),
    }),
    "editor.quickSuggestionsDelay": int().check(
      minimum(0),
      maximum(1073741824)
    ),
    "editor.renameOnType": boolean(),
    "editor.renderRichScreenReaderContent": boolean(),
    "editor.renderControlCharacters": boolean(),
    "editor.renderFinalNewline": zenum(["off", "on", "dimmed"]),
    "editor.renderLineHighlight": zenum(["none", "gutter", "line", "all"]),
    "editor.renderLineHighlightOnlyWhenFocus": boolean(),
    "editor.renderWhitespace": zenum([
      "none",
      "boundary",
      "selection",
      "trailing",
      "all",
    ]),
    "editor.roundedSelection": boolean(),
    "editor.rulers": array(
      union([
        number(),
        union([
          object({
            column: number(),
            color: string(),
          }),
        ]),
      ])
    ),
    "editor.scrollbar.vertical": zenum(["auto", "visible", "hidden"]),
    "editor.scrollbar.horizontal": zenum(["auto", "visible", "hidden"]),
    "editor.scrollbar.verticalScrollbarSize": number(),
    "editor.scrollbar.horizontalScrollbarSize": number(),
    "editor.scrollbar.scrollByPage": boolean(),
    "editor.scrollbar.ignoreHorizontalScrollbarInContentHeight": boolean(),
    "editor.scrollBeyondLastColumn": int().check(
      minimum(0),
      maximum(1073741824)
    ),
    "editor.scrollBeyondLastLine": boolean(),
    "editor.scrollPredominantAxis": boolean(),
    "editor.selectionHighlight": boolean(),
    "editor.selectionHighlightMaxLength": int().check(
      minimum(0),
      maximum(1073741824)
    ),
    "editor.selectionHighlightMultiline": boolean(),
    "editor.showFoldingControls": zenum(["always", "never", "mouseover"]),
    "editor.showUnused": boolean(),
    "editor.snippetSuggestions": zenum(["top", "bottom", "inline", "none"]),
    "editor.smartSelect.selectLeadingAndTrailingWhitespace": boolean(),
    "editor.smartSelect.selectSubwords": boolean(),
    "editor.smoothScrolling": boolean(),
    "editor.stickyScroll.enabled": boolean(),
    "editor.stickyScroll.maxLineCount": number().check(minimum(1), maximum(20)),
    "editor.stickyScroll.defaultModel": zenum([
      "outlineModel",
      "foldingProviderModel",
      "indentationModel",
    ]),
    "editor.stickyScroll.scrollWithEditor": boolean(),
    "editor.stickyTabStops": boolean(),
    "editor.suggest.insertMode": zenum(["insert", "replace"]),
    "editor.suggest.filterGraceful": boolean(),
    "editor.suggest.localityBonus": boolean(),
    "editor.suggest.shareSuggestSelections": boolean(),
    "editor.suggest.selectionMode": zenum([
      "always",
      "never",
      "whenTriggerCharacter",
      "whenQuickSuggestion",
    ]),
    "editor.suggest.snippetsPreventQuickSuggestions": boolean(),
    "editor.suggest.showIcons": boolean(),
    "editor.suggest.showStatusBar": boolean(),
    "editor.suggest.preview": boolean(),
    "editor.suggest.showInlineDetails": boolean(),
    "editor.suggest.maxVisibleSuggestions": number(),
    "editor.suggest.filteredTypes": object({}),
    "editor.suggest.showMethods": boolean(),
    "editor.suggest.showFunctions": boolean(),
    "editor.suggest.showConstructors": boolean(),
    "editor.suggest.showDeprecated": boolean(),
    "editor.suggest.matchOnWordStartOnly": boolean(),
    "editor.suggest.showFields": boolean(),
    "editor.suggest.showVariables": boolean(),
    "editor.suggest.showClasses": boolean(),
    "editor.suggest.showStructs": boolean(),
    "editor.suggest.showInterfaces": boolean(),
    "editor.suggest.showModules": boolean(),
    "editor.suggest.showProperties": boolean(),
    "editor.suggest.showEvents": boolean(),
    "editor.suggest.showOperators": boolean(),
    "editor.suggest.showUnits": boolean(),
    "editor.suggest.showValues": boolean(),
    "editor.suggest.showConstants": boolean(),
    "editor.suggest.showEnums": boolean(),
    "editor.suggest.showEnumMembers": boolean(),
    "editor.suggest.showKeywords": boolean(),
    "editor.suggest.showWords": boolean(),
    "editor.suggest.showColors": boolean(),
    "editor.suggest.showFiles": boolean(),
    "editor.suggest.showReferences": boolean(),
    "editor.suggest.showCustomcolors": boolean(),
    "editor.suggest.showFolders": boolean(),
    "editor.suggest.showTypeParameters": boolean(),
    "editor.suggest.showSnippets": boolean(),
    "editor.suggest.showUsers": boolean(),
    "editor.suggest.showIssues": boolean(),
    "editor.suggestFontSize": int().check(minimum(0), maximum(1000)),
    "editor.suggestLineHeight": int().check(minimum(0), maximum(1000)),
    "editor.suggestOnTriggerCharacters": boolean(),
    "editor.suggestSelection": zenum([
      "first",
      "recentlyUsed",
      "recentlyUsedByPrefix",
    ]),
    "editor.tabCompletion": zenum(["on", "off", "onlySnippets"]),
    "editor.trimWhitespaceOnDelete": boolean(),
    "editor.unicodeHighlight.nonBasicASCII": union([
      boolean(),
      literal("inUntrustedWorkspace"),
    ]),
    "editor.unicodeHighlight.invisibleCharacters": boolean(),
    "editor.unicodeHighlight.ambiguousCharacters": boolean(),
    "editor.unicodeHighlight.includeComments": union([
      boolean(),
      literal("inUntrustedWorkspace"),
    ]),
    "editor.unicodeHighlight.includeStrings": union([
      boolean(),
      literal("inUntrustedWorkspace"),
    ]),
    "editor.unicodeHighlight.allowedCharacters": object({}),
    "editor.unicodeHighlight.allowedLocales": object({}),
    "editor.unusualLineTerminators": zenum(["auto", "off", "prompt"]),
    "editor.useTabStops": boolean(),
    "editor.wordBreak": zenum(["normal", "keepAll"]),
    "editor.wordSegmenterLocales": array(string()),
    "editor.wordSeparators": string(),
    "editor.wordWrap": zenum(["off", "on", "wordWrapColumn", "bounded"]),
    "editor.wordWrapColumn": int().check(minimum(1), maximum(1073741824)),
    "editor.wrappingIndent": zenum(["none", "same", "indent", "deepIndent"]),
    "editor.wrappingStrategy": zenum(["simple", "advanced"]),
    "editor.showDeprecated": boolean(),
    "editor.inertialScroll": boolean(),
    "editor.inlayHints.enabled": zenum([
      "on",
      "onUnlessPressed",
      "offUnlessPressed",
      "off",
    ]),
    "editor.inlayHints.fontSize": number(),
    "editor.inlayHints.fontFamily": string(),
    "editor.inlayHints.padding": boolean(),
    "editor.inlayHints.maximumLength": number(),
    "editor.wrapOnEscapedLineFeeds": boolean(),
    "editor.tabFocusMode": boolean(),
    "editor.defaultColorDecorators": zenum(["auto", "always", "never"]),
    "editor.colorDecoratorsActivatedOn": zenum([
      "clickAndHover",
      "hover",
      "click",
    ]),
    "editor.inlineCompletionsAccessibilityVerbose": boolean(),
    "editor.scrollOnMiddleClick": boolean(),
    "editor.codeActionWidget.showHeaders": boolean(),
    "editor.codeActionWidget.includeNearbyQuickFixes": boolean(),
    "editor.codeActions.triggerOnFocusChange": boolean(),
    "editor.rename.enablePreview": boolean(),
    "editor.defaultFormatter": nullable(
      zenum([
        "ms-vscode.cpptools",
        "vscode.css-language-features",
        "vscode.html-language-features",
        "vscode.json-language-features",
        "vscode.markdown-language-features",
        "vscode.markdown-math",
        "vscode.php-language-features",
        "DEVSENSE.phptools-vscode",
        "esbenp.prettier-vscode",
        "Prisma.prisma",
        "humao.rest-client",
        "slevesque.shader",
        "mxsdev.typescript-explorer",
        "vscode.typescript-language-features",
        "dbaeumer.vscode-eslint",
        "toba.vsfire",
        "ms-vscode.azure-repos",
        "alefragnani.Bookmarks",
        "vscode.configuration-editing",
        "vscode.debug-auto-launch",
        "vscode.debug-server-ready",
        "vscode.emmet",
        "vitest.explorer",
        "vscode.extension-editing",
        "vscode.git",
        "vscode.git-base",
        "mhutchie.git-graph",
        "vscode.github",
        "vscode.github-authentication",
        "vscode.grunt",
        "vscode.gulp",
        "ms-vscode.hexeditor",
        "vscode.ipynb",
        "vscode.jake",
        "ms-vscode.js-debug",
        "ms-vscode.js-debug-companion",
        "ms-vscode.live-server",
        "PKief.material-icon-theme",
        "vscode.media-preview",
        "vscode.merge-conflict",
        "vscode.mermaid-chat-features",
        "vscode.microsoft-authentication",
        "vscode.npm",
        "igordvlpr.open-in-browser",
        "vscode.references-view",
        "ms-vscode.remote-repositories",
        "GitHub.remotehub",
        "vscode.search-result",
        "assisrMatheus.sidebar-markdown-notes",
        "vscode.simple-browser",
        "qwtel.sqlite-viewer",
        "vscode.terminal-suggest",
        "vscode.tunnel-forwarding",
        "ms-vscode.vscode-js-profile-table",
        "bradlc.vscode-tailwindcss",
      ])
    ),
    "editor.formatOnSave": boolean(),
    "editor.formatOnSaveMode": zenum([
      "file",
      "modifications",
      "modificationsIfAvailable",
    ]),
    "editor.snippets.codeActions.enabled": boolean(),
    "editor.defaultFoldingRangeProvider": nullable(
      zenum([
        "ms-vscode.cpptools",
        "vscode.css-language-features",
        "vscode.html-language-features",
        "vscode.json-language-features",
        "vscode.markdown-language-features",
        "vscode.markdown-math",
        "vscode.php-language-features",
        "DEVSENSE.phptools-vscode",
        "Prisma.prisma",
        "humao.rest-client",
        "slevesque.shader",
        "mxsdev.typescript-explorer",
        "vscode.typescript-language-features",
        "dbaeumer.vscode-eslint",
        "toba.vsfire",
        "ms-vscode.azure-repos",
        "alefragnani.Bookmarks",
        "vscode.configuration-editing",
        "vscode.debug-auto-launch",
        "vscode.debug-server-ready",
        "vscode.emmet",
        "vitest.explorer",
        "vscode.extension-editing",
        "vscode.git",
        "vscode.git-base",
        "mhutchie.git-graph",
        "vscode.github",
        "vscode.github-authentication",
        "vscode.grunt",
        "vscode.gulp",
        "ms-vscode.hexeditor",
        "vscode.ipynb",
        "vscode.jake",
        "ms-vscode.js-debug",
        "ms-vscode.js-debug-companion",
        "ms-vscode.live-server",
        "PKief.material-icon-theme",
        "vscode.media-preview",
        "vscode.merge-conflict",
        "vscode.mermaid-chat-features",
        "vscode.microsoft-authentication",
        "vscode.npm",
        "igordvlpr.open-in-browser",
        "esbenp.prettier-vscode",
        "vscode.references-view",
        "ms-vscode.remote-repositories",
        "GitHub.remotehub",
        "vscode.search-result",
        "assisrMatheus.sidebar-markdown-notes",
        "vscode.simple-browser",
        "qwtel.sqlite-viewer",
        "vscode.terminal-suggest",
        "vscode.tunnel-forwarding",
        "ms-vscode.vscode-js-profile-table",
        "bradlc.vscode-tailwindcss",
      ])
    ),
    "editor.dropIntoEditor.preferences": array(
      union([
        string(),
        zenum([
          "text.plain",
          "uri.path.absolute",
          "uri.path.relative",
          "markdown.link",
          "markdown.link.uri",
          "markdown.link.image",
          "markdown.link.audio",
          "markdown.link.video",
        ]),
      ])
    ),
    "editor.aiStats.enabled": boolean(),
  })
);

export class EditorSettingsManager {
  #lastErrors: string[] = [];
  #config: EditorSettings = { ...defaultEditorSettings };

  readonly helpUrl: string =
    "https://code.visualstudio.com/docs/configure/settings#_settings-json-file";

  private updateEditorSettings(config: EditorSettings) {
    this.#config = mergeDefined(defaultEditorSettings, config);
  }

  private parseEditorSettings(json: string): EditorSettings | null {
    this.#lastErrors = [];

    let jsonData: unknown;
    try {
      jsonData = JSON.parse(json);
    } catch (err) {
      this.#lastErrors.push((err as Error).message);
      return null;
    }

    const editorConfigParsed = editorSettingsSchema.safeParse(jsonData);
    if (!editorConfigParsed.success) {
      this.#lastErrors.push(
        ...prettifyError(editorConfigParsed.error).split("\n")
      );
      return null;
    }

    const cfg = editorConfigParsed.data;

    // map "editor.*" settings json pattern to Monaco Editor settings object:
    const editorSettings: EditorSettings = {
      // IEditorOptions
      acceptSuggestionOnCommitCharacter:
        cfg["editor.acceptSuggestionOnCommitCharacter"],
      acceptSuggestionOnEnter: cfg["editor.acceptSuggestionOnEnter"],
      accessibilityPageSize: cfg["editor.accessibilityPageSize"],
      accessibilitySupport: cfg["editor.accessibilitySupport"],
      allowOverflow: undefined,
      allowVariableFonts: cfg["editor.allowVariableFonts"],
      allowVariableFontsInAccessibilityMode:
        cfg["editor.allowVariableFontsInAccessibilityMode"],
      allowVariableLineHeights: cfg["editor.allowVariableLineHeights"],
      ariaLabel: undefined,
      ariaRequired: undefined,
      autoClosingBrackets: cfg["editor.autoClosingBrackets"],
      autoClosingComments: cfg["editor.autoClosingComments"],
      autoClosingDelete: cfg["editor.autoClosingDelete"],
      autoClosingOvertype: cfg["editor.autoClosingOvertype"],
      autoClosingQuotes: cfg["editor.autoClosingQuotes"],
      autoIndent: cfg["editor.autoIndent"],
      autoIndentOnPaste: cfg["editor.autoIndentOnPaste"],
      autoIndentOnPasteWithinString:
        cfg["editor.autoIndentOnPasteWithinString"],
      automaticLayout: undefined,
      autoSurround: cfg["editor.autoSurround"],
      bracketPairColorization: {
        enabled: cfg["editor.bracketPairColorization.enabled"],
        independentColorPoolPerBracketType:
          cfg[
            "editor.bracketPairColorization.independentColorPoolPerBracketType"
          ],
      },
      codeActionsOnSaveTimeout: undefined,
      codeLens: cfg["editor.codeLens"],
      codeLensFontFamily: cfg["editor.codeLensFontFamily"],
      codeLensFontSize: cfg["editor.codeLensFontSize"],
      colorDecorators: cfg["editor.colorDecorators"],
      colorDecoratorsActivatedOn: cfg["editor.colorDecoratorsActivatedOn"],
      colorDecoratorsLimit: cfg["editor.colorDecoratorsLimit"],
      columnSelection: cfg["editor.columnSelection"],
      comments: {
        ignoreEmptyLines: cfg["editor.comments.ignoreEmptyLines"],
        insertSpace: cfg["editor.comments.insertSpace"],
      },
      contextmenu: undefined,
      copyWithSyntaxHighlighting: cfg["editor.copyWithSyntaxHighlighting"],
      cursorBlinking: cfg["editor.cursorBlinking"],
      cursorHeight: cfg["editor.cursorHeight"],
      cursorSmoothCaretAnimation: cfg["editor.cursorSmoothCaretAnimation"],
      cursorStyle: cfg["editor.cursorStyle"],
      cursorSurroundingLines: cfg["editor.cursorSurroundingLines"],
      cursorSurroundingLinesStyle: cfg["editor.cursorSurroundingLinesStyle"],
      cursorWidth: cfg["editor.cursorWidth"],
      defaultColorDecorators: cfg["editor.defaultColorDecorators"],
      definitionLinkOpensInPeek: cfg["editor.definitionLinkOpensInPeek"],
      disableLayerHinting: undefined,
      disableMonospaceOptimizations: undefined,
      domReadOnly: undefined,
      dragAndDrop: cfg["editor.dragAndDrop"],
      dropIntoEditor: {
        enabled: cfg["editor.dropIntoEditor.enabled"],
        showDropSelector: cfg["editor.dropIntoEditor.showDropSelector"],
      },
      editContext: cfg["editor.editContext"],
      emptySelectionClipboard: cfg["editor.emptySelectionClipboard"],
      experimentalGpuAcceleration: cfg["editor.experimentalGpuAcceleration"],
      experimentalWhitespaceRendering:
        cfg["editor.experimentalWhitespaceRendering"],
      extraEditorClassName: undefined,
      fastScrollSensitivity: cfg["editor.fastScrollSensitivity"],
      find: {
        addExtraSpaceOnTop: cfg["editor.find.addExtraSpaceOnTop"],
        autoFindInSelection: cfg["editor.find.autoFindInSelection"],
        cursorMoveOnType: cfg["editor.find.cursorMoveOnType"],
        findOnType: cfg["editor.find.findOnType"],
        loop: cfg["editor.find.loop"],
        seedSearchStringFromSelection:
          cfg["editor.find.seedSearchStringFromSelection"],
      },
      fixedOverflowWidgets: undefined,
      folding: cfg["editor.folding"],
      foldingHighlight: cfg["editor.foldingHighlight"],
      foldingImportsByDefault: cfg["editor.foldingImportsByDefault"],
      foldingMaximumRegions: cfg["editor.foldingMaximumRegions"],
      foldingStrategy: cfg["editor.foldingStrategy"],
      fontFamily: cfg["editor.fontFamily"],
      fontLigatures: cfg["editor.fontLigatures"],
      fontSize: cfg["editor.fontSize"],
      fontVariations: cfg["editor.fontVariations"],
      fontWeight: String(cfg["editor.fontWeight"]),
      formatOnPaste: cfg["editor.formatOnPaste"],
      formatOnType: cfg["editor.formatOnType"],
      glyphMargin: cfg["editor.glyphMargin"],
      gotoLocation: {
        alternativeDeclarationCommand:
          cfg["editor.gotoLocation.alternativeDeclarationCommand"],
        alternativeDefinitionCommand:
          cfg["editor.gotoLocation.alternativeDefinitionCommand"],
        alternativeImplementationCommand:
          cfg["editor.gotoLocation.alternativeImplementationCommand"],
        alternativeReferenceCommand:
          cfg["editor.gotoLocation.alternativeReferenceCommand"],
        alternativeTestsCommand: undefined,
        alternativeTypeDefinitionCommand:
          cfg["editor.gotoLocation.alternativeTypeDefinitionCommand"],
        multiple: undefined,
        multipleDeclarations: cfg["editor.gotoLocation.multipleDeclarations"],
        multipleDefinitions: cfg["editor.gotoLocation.multipleDefinitions"],
        multipleImplementations:
          cfg["editor.gotoLocation.multipleImplementations"],
        multipleReferences: cfg["editor.gotoLocation.multipleReferences"],
        multipleTests: undefined,
        multipleTypeDefinitions:
          cfg["editor.gotoLocation.multipleTypeDefinitions"],
      },
      guides: {
        bracketPairs: cfg["editor.guides.bracketPairs"],
        bracketPairsHorizontal: cfg["editor.guides.bracketPairsHorizontal"],
        highlightActiveBracketPair:
          cfg["editor.guides.highlightActiveBracketPair"],
        highlightActiveIndentation:
          cfg["editor.guides.highlightActiveIndentation"],
        indentation: cfg["editor.guides.indentation"],
      },
      hideCursorInOverviewRuler: cfg["editor.hideCursorInOverviewRuler"],
      hover: {
        above: cfg["editor.hover.above"],
        delay: cfg["editor.hover.delay"],
        enabled: cfg["editor.hover.enabled"],
        hidingDelay: cfg["editor.hover.hidingDelay"],
        sticky: cfg["editor.hover.sticky"],
      },
      inDiffEditor: undefined,
      inertialScroll: cfg["editor.inertialScroll"],
      inlayHints: {
        enabled: cfg["editor.inlayHints.enabled"],
        fontFamily: cfg["editor.inlayHints.fontFamily"],
        fontSize: cfg["editor.inlayHints.fontSize"],
        maximumLength: cfg["editor.inlayHints.maximumLength"],
        padding: cfg["editor.inlayHints.padding"],
      },
      inlineCompletionsAccessibilityVerbose:
        cfg["editor.inlineCompletionsAccessibilityVerbose"],
      inlineSuggest: {
        enabled: cfg["editor.inlineSuggest.enabled"],
        fontFamily: cfg["editor.inlineSuggest.fontFamily"],
        keepOnBlur: undefined,
        minShowDelay: cfg["editor.inlineSuggest.minShowDelay"],
        mode: undefined,
        showToolbar: cfg["editor.inlineSuggest.showToolbar"],
        suppressInSnippetMode:
          cfg["editor.inlineSuggest.suppressInSnippetMode"],
        suppressSuggestions: cfg["editor.inlineSuggest.suppressSuggestions"],
        syntaxHighlightingEnabled:
          cfg["editor.inlineSuggest.syntaxHighlightingEnabled"],
      },
      letterSpacing: cfg["editor.letterSpacing"],
      lightbulb: {
        enabled: cfg[
          "editor.lightbulb.enabled"
        ] as MonacoEditor.ShowLightbulbIconMode,
      },
      lineDecorationsWidth: undefined,
      lineHeight: cfg["editor.lineHeight"],
      lineNumbers: cfg["editor.lineNumbers"],
      lineNumbersMinChars: undefined,
      linkedEditing: cfg["editor.linkedEditing"],
      links: cfg["editor.links"],
      matchBrackets: cfg["editor.matchBrackets"],
      matchOnWordStartOnly: cfg["editor.suggest.matchOnWordStartOnly"],
      minimap: {
        autohide: cfg["editor.minimap.autohide"],
        enabled: cfg["editor.minimap.enabled"],
        markSectionHeaderRegex: cfg["editor.minimap.markSectionHeaderRegex"],
        maxColumn: cfg["editor.minimap.maxColumn"],
        renderCharacters: cfg["editor.minimap.renderCharacters"],
        scale: cfg["editor.minimap.scale"],
        sectionHeaderFontSize: cfg["editor.minimap.sectionHeaderFontSize"],
        sectionHeaderLetterSpacing:
          cfg["editor.minimap.sectionHeaderLetterSpacing"],
        showMarkSectionHeaders: cfg["editor.minimap.showMarkSectionHeaders"],
        showRegionSectionHeaders:
          cfg["editor.minimap.showRegionSectionHeaders"],
        showSlider: cfg["editor.minimap.showSlider"],
        side: cfg["editor.minimap.side"],
        size: cfg["editor.minimap.size"],
      },
      mouseMiddleClickAction: cfg["editor.mouseMiddleClickAction"],
      mouseStyle: undefined,
      mouseWheelScrollSensitivity: cfg["editor.mouseWheelScrollSensitivity"],
      mouseWheelZoom: cfg["editor.mouseWheelZoom"],
      multiCursorLimit: cfg["editor.multiCursorLimit"],
      multiCursorMergeOverlapping: cfg["editor.multiCursorMergeOverlapping"],
      multiCursorModifier: cfg["editor.multiCursorModifier"],
      multiCursorPaste: cfg["editor.multiCursorPaste"],
      occurrencesHighlight: cfg["editor.occurrencesHighlight"],
      occurrencesHighlightDelay: cfg["editor.occurrencesHighlightDelay"],
      overtypeCursorStyle: cfg["editor.overtypeCursorStyle"],
      overtypeOnPaste: cfg["editor.overtypeOnPaste"],
      overviewRulerBorder: cfg["editor.overviewRulerBorder"],
      overviewRulerLanes: undefined,
      padding: {
        bottom: cfg["editor.padding.bottom"],
        top: cfg["editor.padding.top"],
      },
      parameterHints: {
        cycle: cfg["editor.parameterHints.cycle"],
        enabled: cfg["editor.parameterHints.enabled"],
      },
      pasteAs: {
        enabled: cfg["editor.pasteAs.enabled"],
        showPasteSelector: cfg["editor.pasteAs.showPasteSelector"],
      },
      peekWidgetDefaultFocus: cfg["editor.peekWidgetDefaultFocus"],
      placeholder: undefined,
      quickSuggestions: cfg["editor.quickSuggestions"],
      quickSuggestionsDelay: cfg["editor.quickSuggestionsDelay"],
      readOnly: undefined,
      readOnlyMessage: undefined,
      renameOnType: cfg["editor.renameOnType"],
      renderControlCharacters: cfg["editor.renderControlCharacters"],
      renderFinalNewline: cfg["editor.renderFinalNewline"],
      renderLineHighlight: cfg["editor.renderLineHighlight"],
      renderLineHighlightOnlyWhenFocus:
        cfg["editor.renderLineHighlightOnlyWhenFocus"],
      renderRichScreenReaderContent:
        cfg["editor.renderRichScreenReaderContent"],
      renderValidationDecorations: undefined,
      renderWhitespace: cfg["editor.renderWhitespace"],
      revealHorizontalRightPadding: undefined,
      roundedSelection: cfg["editor.roundedSelection"],
      rulers: cfg["editor.rulers"],
      screenReaderAnnounceInlineSuggestion:
        cfg["editor.screenReaderAnnounceInlineSuggestion"],
      scrollbar: {
        alwaysConsumeMouseWheel: undefined,
        arrowSize: undefined,
        handleMouseWheel: undefined,
        horizontal: cfg["editor.scrollbar.horizontal"],
        horizontalHasArrows: undefined,
        horizontalScrollbarSize:
          cfg["editor.scrollbar.horizontalScrollbarSize"],
        horizontalSliderSize: undefined,
        ignoreHorizontalScrollbarInContentHeight:
          cfg["editor.scrollbar.ignoreHorizontalScrollbarInContentHeight"],
        scrollByPage: cfg["editor.scrollbar.scrollByPage"],
        useShadows: undefined,
        vertical: cfg["editor.scrollbar.vertical"],
        verticalHasArrows: undefined,
        verticalScrollbarSize: cfg["editor.scrollbar.verticalScrollbarSize"],
        verticalSliderSize: undefined,
      },
      scrollBeyondLastColumn: cfg["editor.scrollBeyondLastColumn"],
      scrollBeyondLastLine: cfg["editor.scrollBeyondLastLine"],
      scrollOnMiddleClick: cfg["editor.scrollOnMiddleClick"],
      scrollPredominantAxis: cfg["editor.scrollPredominantAxis"],
      selectionClipboard: undefined,
      selectionHighlight: cfg["editor.selectionHighlight"],
      selectionHighlightMaxLength: cfg["editor.selectionHighlightMaxLength"],
      selectionHighlightMultiline: cfg["editor.selectionHighlightMultiline"],
      selectOnLineNumbers: undefined,
      showDeprecated: cfg["editor.showDeprecated"],
      showFoldingControls: cfg["editor.showFoldingControls"],
      showUnused: cfg["editor.showUnused"],
      smartSelect: {
        selectLeadingAndTrailingWhitespace:
          cfg["editor.smartSelect.selectLeadingAndTrailingWhitespace"],
        selectSubwords: cfg["editor.smartSelect.selectSubwords"],
      },
      smoothScrolling: cfg["editor.smoothScrolling"],
      snippetSuggestions: cfg["editor.snippetSuggestions"],
      stickyScroll: {
        defaultModel: cfg["editor.stickyScroll.defaultModel"],
        enabled: cfg["editor.stickyScroll.enabled"],
        maxLineCount: cfg["editor.stickyScroll.maxLineCount"],
        scrollWithEditor: cfg["editor.stickyScroll.scrollWithEditor"],
      },
      stickyTabStops: cfg["editor.stickyTabStops"],
      stopRenderingLineAfter: undefined,
      suggest: {
        filterGraceful: cfg["editor.suggest.filterGraceful"],
        insertMode: cfg["editor.suggest.insertMode"],
        localityBonus: cfg["editor.suggest.localityBonus"],
        matchOnWordStartOnly: cfg["editor.suggest.matchOnWordStartOnly"],
        preview: cfg["editor.suggest.preview"],
        previewMode: undefined,
        selectionMode: cfg["editor.suggest.selectionMode"],
        shareSuggestSelections: cfg["editor.suggest.shareSuggestSelections"],
        showClasses: cfg["editor.suggest.showClasses"],
        showColors: cfg["editor.suggest.showColors"],
        showConstants: cfg["editor.suggest.showConstants"],
        showConstructors: cfg["editor.suggest.showConstructors"],
        showDeprecated: cfg["editor.suggest.showDeprecated"],
        showEnumMembers: cfg["editor.suggest.showEnumMembers"],
        showEnums: cfg["editor.suggest.showEnums"],
        showEvents: cfg["editor.suggest.showEvents"],
        showFields: cfg["editor.suggest.showFields"],
        showFiles: cfg["editor.suggest.showFiles"],
        showFolders: cfg["editor.suggest.showFolders"],
        showFunctions: cfg["editor.suggest.showFunctions"],
        showIcons: cfg["editor.suggest.showIcons"],
        showInlineDetails: cfg["editor.suggest.showInlineDetails"],
        showInterfaces: cfg["editor.suggest.showInterfaces"],
        showIssues: cfg["editor.suggest.showIssues"],
        showKeywords: cfg["editor.suggest.showKeywords"],
        showMethods: cfg["editor.suggest.showMethods"],
        showModules: cfg["editor.suggest.showModules"],
        showOperators: cfg["editor.suggest.showOperators"],
        showProperties: cfg["editor.suggest.showProperties"],
        showReferences: cfg["editor.suggest.showReferences"],
        showSnippets: cfg["editor.suggest.showSnippets"],
        showStatusBar: cfg["editor.suggest.showStatusBar"],
        showStructs: cfg["editor.suggest.showStructs"],
        showTypeParameters: cfg["editor.suggest.showTypeParameters"],
        showUnits: cfg["editor.suggest.showUnits"],
        showUsers: cfg["editor.suggest.showUsers"],
        showValues: cfg["editor.suggest.showValues"],
        showVariables: cfg["editor.suggest.showVariables"],
        showWords: cfg["editor.suggest.showWords"],
        snippetsPreventQuickSuggestions:
          cfg["editor.suggest.snippetsPreventQuickSuggestions"],
      },
      suggestFontSize: cfg["editor.suggestFontSize"],
      suggestLineHeight: cfg["editor.suggestLineHeight"],
      suggestOnTriggerCharacters: cfg["editor.suggestOnTriggerCharacters"],
      suggestSelection: cfg["editor.suggestSelection"],
      tabCompletion: cfg["editor.tabCompletion"],
      tabFocusMode: cfg["editor.tabFocusMode"],
      tabIndex: undefined,
      trimWhitespaceOnDelete: cfg["editor.trimWhitespaceOnDelete"],
      unfoldOnClickAfterEndOfLine: cfg["editor.unfoldOnClickAfterEndOfLine"],
      unicodeHighlight: {
        allowedCharacters: cfg["editor.unicodeHighlight.allowedCharacters"],
        allowedLocales: cfg["editor.unicodeHighlight.allowedLocales"],
        ambiguousCharacters: cfg["editor.unicodeHighlight.ambiguousCharacters"],
        includeComments: cfg["editor.unicodeHighlight.includeComments"],
        includeStrings: cfg["editor.unicodeHighlight.includeStrings"],
        invisibleCharacters: cfg["editor.unicodeHighlight.invisibleCharacters"],
        nonBasicASCII: cfg["editor.unicodeHighlight.nonBasicASCII"],
      },
      unusualLineTerminators: cfg["editor.unusualLineTerminators"],
      useShadowDOM: undefined,
      useTabStops: cfg["editor.useTabStops"],
      wordBreak: cfg["editor.wordBreak"],
      wordSegmenterLocales: cfg["editor.wordSegmenterLocales"],
      wordSeparators: cfg["editor.wordSeparators"],
      wordWrap: cfg["editor.wordWrap"],
      wordWrapBreakAfterCharacters: undefined,
      wordWrapBreakBeforeCharacters: undefined,
      wordWrapColumn: cfg["editor.wordWrapColumn"],
      wordWrapOverride1: undefined,
      wordWrapOverride2: undefined,
      wrapOnEscapedLineFeeds: cfg["editor.wrapOnEscapedLineFeeds"],
      wrappingIndent: cfg["editor.wrappingIndent"],
      wrappingStrategy: cfg["editor.wrappingStrategy"],

      // IStandaloneEditorConstructionOptions - IEditorOptions
      "semanticHighlighting.enabled":
        cfg["editor.semanticHighlighting.enabled"],
      accessibilityHelpUrl: undefined,
      ariaContainerElement: undefined,
      autoDetectHighContrast: undefined,
      detectIndentation: cfg["editor.detectIndentation"],
      dimension: undefined,
      insertSpaces: cfg["editor.insertSpaces"],
      language: undefined,
      largeFileOptimizations: cfg["editor.largeFileOptimizations"],
      maxTokenizationLineLength: cfg["editor.maxTokenizationLineLength"],
      model: undefined,
      overflowWidgetsDomNode: undefined,
      stablePeek: cfg["editor.stablePeek"],
      tabSize: cfg["editor.tabSize"],
      theme: undefined,
      trimAutoWhitespace: cfg["editor.trimAutoWhitespace"],
      value: undefined,
      wordBasedSuggestions: cfg["editor.wordBasedSuggestions"],
      wordBasedSuggestionsOnlySameLanguage: undefined,
    };

    return editorSettings;
  }

  validateEditorSettings(json: string): boolean {
    return !!this.parseEditorSettings(json);
  }

  setEditorSettings(json: string): boolean {
    const config = this.parseEditorSettings(json);
    if (!config) {
      this.revokeEditorSettings();
      return false;
    }

    this.updateEditorSettings(config);
    return true;
  }

  getEditorSettings() {
    return this.#config;
  }

  revokeEditorSettings() {
    this.updateEditorSettings({});
  }

  getErrors(): string[] {
    return this.#lastErrors;
  }
}

export const editorSettingsManager = new EditorSettingsManager();
